### ISSUE TITLE
Getting channel info error

### ISSUE THREAD

**Issue by rozza591** [gitbugr/EPG-Scraper-XMLTV-Kodi-#17]
Hey, I've ran through the setup and the gist template is being saved successfully but im receiving the following error and the xml no the gist is empty.
`Getting channel info...{"status":0,"errors":[{"code":"-1","message":"Unknown error: \"undefined\""}]}`

Any help would be appreciated.

**Comment by gitbugr** [comment]
Hey @rozza591, it looks like they've updated their api (it's not a public API, so we can't really rely on it being stable.) - I've just pushed [9a72f68d](https://github.com/gitbugr/sky-epg-xmltv-kodi/commit/9a72f68da316f89f1b46a0040dd2e2432c348064) which should fix the script. I haven't used the script in quite a while, but I'll do my best to update it as long as these sorts of issues are raised. Let me know if it works for you!

**Comment by rozza591** [comment]
Awesome I appreciate your work, thanks!

**Comment by gitbugr** [comment]
Gonna close the issue for now, any more issues, lmk! :)
