### ISSUE TITLE
Program Data Incorrect

### ISSUE THREAD

**Issue by rozza591** [gitbugr/EPG-Scraper-XMLTV-Kodi-#19]
Not sure if theres an issue with the formatting but when I import the EPG each channel just says the name of the channel and not the actual Guide data. I've checked the EPG which was output and there is Guide data in there. Confused why Plex is interpreting the titles as the data

**Comment by gitbugr** [comment]
Hmm, that's strange. I initially wrote this for Kodi, so haven't tested Plex. Will take a look shortly and get back to you.

**Comment by gitbugr** [comment]
Should be fixed in [32a6f647](https://github.com/gitbugr/sky-epg-xmltv-kodi/commit/32a6f6470e3631a09587eb0ae8dd98f5a45dc175) - Was a small date formatting issue that Plex doesn't like. I've also added support for icons if available in Sky's data.

You'll need to re-run `npm install` as I've added a new babel plugin to the package.json. Let me know if it works for you!

**Comment by rozza591** [comment]
Very nice, cheers!

**Comment by rozza591** [comment]
Works great but the local save has broken so will take a look at that tomorrow. I need to add some error handling into it and update the README anyway

**Comment by gitbugr** [comment]
Hmm, seemed to work for me (I tested with a local file) - but cool, thanks for that, and glad I could help!

**Comment by rozza591** [comment]
Found it, looks like the switch break was added back in after the Gist save which stopped the local save from occuring, I'll send in a commit for that and the ReadMe but I might have to Fork it as a Plex version after because it looks like Plex wants the episode number on its own tag and not in the description as it won't read it as TV if not. Or I could look at commiting it back to this if its not going to mess up Kodi?

**Comment by rozza591** [comment]
Actually ignore the above I pulled the wrong version, just checked the master tree and theres no break from the Gist Switch
